<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Testman.Core\Testman.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>testman</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(CreateDistributionArchive)' == 'true'">
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <SatelliteResourceLanguages>en;ja;zh-CN</SatelliteResourceLanguages>
    <PublishDir>$(MSBuildProjectDirectory)\..\..\artifacts\publish\win-x64\</PublishDir>
    <DistributionArchivePath>$(MSBuildProjectDirectory)\..\..\artifacts\testman-win-x64.zip</DistributionArchivePath>
  </PropertyGroup>

  <Target Name="CreateDistributionArchive"
          AfterTargets="Publish"
          Condition="'$(CreateDistributionArchive)' == 'true'">
    <ZipDirectory SourceDirectory="$(PublishDir)"
                  DestinationFile="$(DistributionArchivePath)"
                  Overwrite="true" />
  </Target>

</Project>
